# 调试

## `glGetError()`

当 glGetError 被调用时，它要么会返回错误标记之一，要么返回无错误。glGetError 会返回的错误值如下：

|标记|代码|描述|
|---|---|---|
|GL_NO_ERROR|0|自上次调用 glGetError 以来没有错误|
|GL_INVALID_ENUM|1280|枚举参数不合法|
|GL_INVALID_VALUE|1281|值参数不合法|
|GL_INVALID_OPERATION|1282|一个指令的状态对指令的参数不合法|
|GL_STACK_OVERFLOW|1283|压栈操作造成栈上溢 (Overflow)|
|GL_STACK_UNDERFLOW|1284|弹栈操作时栈在最低点（译注：即栈下溢 (Underflow)）|
|GL_OUT_OF_MEMORY|1285|内存调用操作无法调用（足够的）内存|
|GL_INVALID_FRAMEBUFFER_OPERATION|1286|读取或写入一个不完整的帧缓冲|
每次调用glGetError，只会返回一个错误标记，但同时清除所有的错误标记。也就是说如果每一帧之后调用 glGetError 一次，它返回一个错误，不能确定这就是唯一的错误，并且错误的来源可能在这一帧的任意地方。

```c++
glBindTexture(GL_TEXTURE_2D, tex);
std::cout << glGetError() << std::endl; // 返回 0 (无错误)

glTexImage2D(GL_TEXTURE_3D, 0, GL_RGB, 512, 512, 0, GL_RGB, GL_UNSIGNED_BYTE, data);
std::cout << glGetError() << std::endl; // 返回 1280 (非法枚举)

glGenTextures(-5, textures);
std::cout << glGetError() << std::endl; // 返回 1281 (非法值)

std::cout << glGetError() << std::endl; // 返回 0 (无错误)
```

⚠️ 注意：GLEW 有一个历史悠久的 bug，调用 `glewInit()` 会设置一个 `GL_INVALID_ENUM` 的错误标记，所以第一次调用的 `glGetError` 永远会猝不及防返回一个错误代码。如果要修复这个 bug，建议调用 `glewInit` 之后立即调用 `glGetError` 消除这个标记：

```
glewInit();
glGetError();
```

## 调试输出

一个叫做调试输出 (Debug Output) 的 OpenGL 拓展是一个非常有用的工具，它在 **4.3** 版本之后变为了核心 OpenGL 的一部分。通过使用调试输出拓展，OpenGL 自身会直接发送一个比起 glGetError 更为完善的错误或警告信息给用户。